/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main (void)
{
  GtkWidget *main;
  GdkPixbuf *main_icon_pixbuf;
  GtkWidget *eventbox2;
  GtkWidget *alignment7;
  GtkWidget *notebook1;
  GtkWidget *eventbox1;
  GtkWidget *hbox1;
  GtkWidget *vbox1;
  GtkWidget *fixed1;
  GtkWidget *image3;
  GtkWidget *runButton;
  GtkWidget *alignment1;
  GtkWidget *hbox2;
  GtkWidget *image1;
  GtkWidget *label9;
  GtkWidget *quitButton;
  GtkWidget *alignment3;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label11;
  GtkWidget *updateButton;
  GtkWidget *alignment4;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label12;
  GtkWidget *stopButton;
  GtkWidget *alignment2;
  GtkWidget *hbox3;
  GtkWidget *image2;
  GtkWidget *label10;
  GtkWidget *scrolledwindow2;
  GtkWidget *resultList;
  GtkWidget *label107;
  GtkWidget *label108;
  GtkWidget *label109;
  GtkWidget *label110;
  GtkWidget *label111;
  GtkWidget *label112;
  GtkWidget *label113;
  GtkWidget *logViewWindow;
  GtkWidget *logView;
  GtkWidget *statusbar1;
  GtkWidget *testLabel;
  GtkWidget *fixed2;
  GtkWidget *testLength;
  GtkWidget *testCycle;
  GtkWidget *panosPerBatch;
  GtkWidget *label14;
  GtkWidget *label29;
  GtkWidget *usb1tolerance;
  GtkWidget *usb2tolerance;
  GtkWidget *usb3tolerance;
  GtkWidget *vgaTolerance;
  GtkWidget *applySettings1;
  GtkWidget *alignment6;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label19;
  GtkWidget *button14;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label92;
  GtkWidget *saveButton;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label91;
  GtkWidget *crcTolerance;
  GtkWidget *prototolerance;
  GtkWidget *label15;
  GtkWidget *enableBatchTesting;
  GtkWidget *label24;
  GtkWidget *label28;
  GtkWidget *label22;
  GtkWidget *label13;
  GtkWidget *protousbtolerance;
  GtkWidget *enableDdrCrcTest;
  GtkWidget *label70;
  GtkWidget *enableVgaDdrTest;
  GtkWidget *enableUsb1Test;
  GtkWidget *enableUsb2Test;
  GtkWidget *enableUsb3Test;
  GtkWidget *enableprototest;
  GtkWidget *enableprotousbtest;
  GtkWidget *label18;
  GtkWidget *fixed3;
  GtkWidget *remoteACsockets;
  GtkWidget *applySettings2;
  GtkWidget *alignment5;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label17;
  GtkWidget *discoverTime;
  GtkWidget *saveButton2;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label94;
  GtkWidget *loadButton2;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label93;
  GtkWidget *discoverIterations;
  GtkWidget *label23;
  GtkWidget *enableRemoteAC;
  GtkWidget *label25;
  GtkWidget *label27;
  GtkWidget *label98;
  GtkWidget *label97;
  GtkWidget *SettingsLabel;

  main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (main), _("Pano Logic BurnIn Test v2.2"));
  main_icon_pixbuf = create_pixbuf ("tile-four.gif");
  if (main_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (main), main_icon_pixbuf);
      gdk_pixbuf_unref (main_icon_pixbuf);
    }

  eventbox2 = gtk_event_box_new ();
  gtk_widget_show (eventbox2);
  gtk_container_add (GTK_CONTAINER (main), eventbox2);

  alignment7 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (eventbox2), alignment7);
  gtk_widget_set_size_request (alignment7, 858, 770);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (alignment7), notebook1);
  gtk_widget_set_size_request (notebook1, 860, 770);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (notebook1), eventbox1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (eventbox1), hbox1);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox1, TRUE, TRUE, 0);
  gtk_widget_set_size_request (vbox1, 543, 743);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 5);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_box_pack_start (GTK_BOX (vbox1), fixed1, TRUE, TRUE, 0);
  gtk_widget_set_size_request (fixed1, -1, 144);

  image3 = create_pixmap (main, "logo.gif");
  gtk_widget_show (image3);
  gtk_fixed_put (GTK_FIXED (fixed1), image3, 16, 8);
  gtk_widget_set_size_request (image3, 208, 88);

  runButton = gtk_button_new ();
  gtk_widget_show (runButton);
  gtk_fixed_put (GTK_FIXED (fixed1), runButton, 256, 16);
  gtk_widget_set_size_request (runButton, 80, 72);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (runButton), alignment1);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox2);

  image1 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox2), image1, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Run"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox2), label9, FALSE, FALSE, 0);

  quitButton = gtk_button_new ();
  gtk_widget_show (quitButton);
  gtk_fixed_put (GTK_FIXED (fixed1), quitButton, 448, 16);
  gtk_widget_set_size_request (quitButton, 80, 72);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (quitButton), alignment3);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Quit"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox4), label11, FALSE, FALSE, 0);

  updateButton = gtk_button_new ();
  gtk_widget_show (updateButton);
  gtk_fixed_put (GTK_FIXED (fixed1), updateButton, 16, 104);
  gtk_widget_set_size_request (updateButton, 208, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (updateButton), alignment4);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Update Results"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox5), label12, FALSE, FALSE, 0);

  stopButton = gtk_button_new ();
  gtk_widget_show (stopButton);
  gtk_fixed_put (GTK_FIXED (fixed1), stopButton, 352, 16);
  gtk_widget_set_size_request (stopButton, 80, 72);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (stopButton), alignment2);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox3);

  image2 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox3), image2, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Stop"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox3), label10, FALSE, FALSE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  resultList = gtk_clist_new (7);
  gtk_widget_show (resultList);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), resultList);
  gtk_widget_set_size_request (resultList, -1, 373);
  gtk_clist_set_column_width (GTK_CLIST (resultList), 0, 132);
  gtk_clist_set_column_width (GTK_CLIST (resultList), 1, 92);
  gtk_clist_set_column_width (GTK_CLIST (resultList), 2, 63);
  gtk_clist_set_column_width (GTK_CLIST (resultList), 3, 92);
  gtk_clist_set_column_width (GTK_CLIST (resultList), 4, 146);
  gtk_clist_set_column_width (GTK_CLIST (resultList), 5, 162);
  gtk_clist_set_column_width (GTK_CLIST (resultList), 6, 80);
  gtk_clist_column_titles_show (GTK_CLIST (resultList));

  label107 = gtk_label_new (_("MAC Address"));
  gtk_widget_show (label107);
  gtk_clist_set_column_widget (GTK_CLIST (resultList), 0, label107);

  label108 = gtk_label_new (_("IP Address"));
  gtk_widget_show (label108);
  gtk_clist_set_column_widget (GTK_CLIST (resultList), 1, label108);

  label109 = gtk_label_new (_("FPGA"));
  gtk_widget_show (label109);
  gtk_clist_set_column_widget (GTK_CLIST (resultList), 2, label109);

  label110 = gtk_label_new (_("Tests Ran"));
  gtk_widget_show (label110);
  gtk_clist_set_column_widget (GTK_CLIST (resultList), 3, label110);

  label111 = gtk_label_new (_("Test Pass Rate"));
  gtk_widget_show (label111);
  gtk_clist_set_column_widget (GTK_CLIST (resultList), 4, label111);

  label112 = gtk_label_new (_("Power Cycle Failures"));
  gtk_widget_show (label112);
  gtk_clist_set_column_widget (GTK_CLIST (resultList), 5, label112);

  label113 = gtk_label_new (_("Status"));
  gtk_widget_show (label113);
  gtk_clist_set_column_widget (GTK_CLIST (resultList), 6, label113);

  logViewWindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (logViewWindow);
  gtk_box_pack_start (GTK_BOX (vbox1), logViewWindow, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (logViewWindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  logView = gtk_text_view_new ();
  gtk_widget_show (logView);
  gtk_container_add (GTK_CONTAINER (logViewWindow), logView);
  gtk_widget_set_size_request (logView, -1, 168);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (logView), FALSE);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (logView), FALSE);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);

  testLabel = gtk_label_new (_("Test"));
  gtk_widget_show (testLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), testLabel);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);
  gtk_widget_set_size_request (fixed2, 860, 736);
  gtk_container_set_border_width (GTK_CONTAINER (fixed2), 1);

  testLength = gtk_entry_new ();
  gtk_widget_show (testLength);
  gtk_fixed_put (GTK_FIXED (fixed2), testLength, 536, 72);
  gtk_widget_set_size_request (testLength, 158, 25);

  testCycle = gtk_entry_new ();
  gtk_widget_show (testCycle);
  gtk_fixed_put (GTK_FIXED (fixed2), testCycle, 536, 120);
  gtk_widget_set_size_request (testCycle, 158, 25);

  panosPerBatch = gtk_entry_new ();
  gtk_widget_show (panosPerBatch);
  gtk_fixed_put (GTK_FIXED (fixed2), panosPerBatch, 536, 240);
  gtk_widget_set_size_request (panosPerBatch, 158, 25);

  label14 = gtk_label_new (_("Total test length (in minutes)"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 112, 72);
  gtk_widget_set_size_request (label14, 168, 24);

  label29 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed2), label29, 728, 72);
  gtk_widget_set_size_request (label29, 104, 24);

  usb1tolerance = gtk_entry_new ();
  gtk_widget_show (usb1tolerance);
  gtk_fixed_put (GTK_FIXED (fixed2), usb1tolerance, 536, 456);
  gtk_widget_set_size_request (usb1tolerance, 158, 25);

  usb2tolerance = gtk_entry_new ();
  gtk_widget_show (usb2tolerance);
  gtk_fixed_put (GTK_FIXED (fixed2), usb2tolerance, 536, 496);
  gtk_widget_set_size_request (usb2tolerance, 158, 25);

  usb3tolerance = gtk_entry_new ();
  gtk_widget_show (usb3tolerance);
  gtk_fixed_put (GTK_FIXED (fixed2), usb3tolerance, 536, 536);
  gtk_widget_set_size_request (usb3tolerance, 158, 25);

  vgaTolerance = gtk_entry_new ();
  gtk_widget_show (vgaTolerance);
  gtk_fixed_put (GTK_FIXED (fixed2), vgaTolerance, 536, 368);
  gtk_widget_set_size_request (vgaTolerance, 158, 25);

  applySettings1 = gtk_button_new ();
  gtk_widget_show (applySettings1);
  gtk_fixed_put (GTK_FIXED (fixed2), applySettings1, 768, 656);
  gtk_widget_set_size_request (applySettings1, 88, 80);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (applySettings1), alignment6);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Apply"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox7), label19, FALSE, FALSE, 0);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed2), button14, 560, 656);
  gtk_widget_set_size_request (button14, 88, 80);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button14), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label92 = gtk_label_new_with_mnemonic (_("Load"));
  gtk_widget_show (label92);
  gtk_box_pack_start (GTK_BOX (hbox9), label92, FALSE, FALSE, 0);

  saveButton = gtk_button_new ();
  gtk_widget_show (saveButton);
  gtk_fixed_put (GTK_FIXED (fixed2), saveButton, 664, 656);
  gtk_widget_set_size_request (saveButton, 88, 80);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (saveButton), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label91 = gtk_label_new_with_mnemonic (_("Save"));
  gtk_widget_show (label91);
  gtk_box_pack_start (GTK_BOX (hbox8), label91, FALSE, FALSE, 0);

  crcTolerance = gtk_entry_new ();
  gtk_widget_show (crcTolerance);
  gtk_fixed_put (GTK_FIXED (fixed2), crcTolerance, 536, 408);
  gtk_widget_set_size_request (crcTolerance, 158, 25);

  prototolerance = gtk_entry_new ();
  gtk_widget_show (prototolerance);
  gtk_fixed_put (GTK_FIXED (fixed2), prototolerance, 536, 576);
  gtk_widget_set_size_request (prototolerance, 158, 25);

  label15 = gtk_label_new (_("Power cycle period (in minutes)"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 96, 120);
  gtk_widget_set_size_request (label15, 216, 24);

  enableBatchTesting = gtk_check_button_new_with_mnemonic (_("Enable Testing in Batches"));
  gtk_widget_show (enableBatchTesting);
  gtk_fixed_put (GTK_FIXED (fixed2), enableBatchTesting, 96, 216);
  gtk_widget_set_size_request (enableBatchTesting, 184, 24);

  label24 = gtk_label_new (_("Number of devices to test at a time"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed2), label24, 104, 240);
  gtk_widget_set_size_request (label24, 224, 32);

  label28 = gtk_label_new (_("Tests"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed2), label28, 416, 312);
  gtk_widget_set_size_request (label28, 41, 17);

  label22 = gtk_label_new (_("Testing in Batches"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed2), label22, 376, 184);
  gtk_widget_set_size_request (label22, 128, 24);

  label13 = gtk_label_new (_("Test Duration"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 368, 24);
  gtk_widget_set_size_request (label13, 136, 32);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  protousbtolerance = gtk_entry_new ();
  gtk_widget_show (protousbtolerance);
  gtk_fixed_put (GTK_FIXED (fixed2), protousbtolerance, 536, 616);
  gtk_widget_set_size_request (protousbtolerance, 158, 25);

  enableDdrCrcTest = gtk_check_button_new_with_mnemonic (_("DDR CRC Test (Rev B/C only)"));
  gtk_widget_show (enableDdrCrcTest);
  gtk_fixed_put (GTK_FIXED (fixed2), enableDdrCrcTest, 104, 400);
  gtk_widget_set_size_request (enableDdrCrcTest, 208, 24);

  label70 = gtk_label_new (_("Tolerance\n"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed2), label70, 552, 336);
  gtk_widget_set_size_request (label70, 120, 24);

  enableVgaDdrTest = gtk_check_button_new_with_mnemonic (_("VGA/DDR Test (Rev A only)"));
  gtk_widget_show (enableVgaDdrTest);
  gtk_fixed_put (GTK_FIXED (fixed2), enableVgaDdrTest, 104, 360);
  gtk_widget_set_size_request (enableVgaDdrTest, 216, 40);

  enableUsb1Test = gtk_check_button_new_with_mnemonic (_("USB Test, Port 1 (Rev A/B Only)\n"));
  gtk_widget_show (enableUsb1Test);
  gtk_fixed_put (GTK_FIXED (fixed2), enableUsb1Test, 104, 448);
  gtk_widget_set_size_request (enableUsb1Test, 215, 31);

  enableUsb2Test = gtk_check_button_new_with_mnemonic (_("USB Test, Port 2 (Rev A/B Only)"));
  gtk_widget_show (enableUsb2Test);
  gtk_fixed_put (GTK_FIXED (fixed2), enableUsb2Test, 104, 488);
  gtk_widget_set_size_request (enableUsb2Test, 223, 23);

  enableUsb3Test = gtk_check_button_new_with_mnemonic (_("USB Test, Port 3 (Rev A/B Only)"));
  gtk_widget_show (enableUsb3Test);
  gtk_fixed_put (GTK_FIXED (fixed2), enableUsb3Test, 104, 528);
  gtk_widget_set_size_request (enableUsb3Test, 223, 31);

  enableprototest = gtk_check_button_new_with_mnemonic (_("USB Protocol Error Test (All Rev)"));
  gtk_widget_show (enableprototest);
  gtk_fixed_put (GTK_FIXED (fixed2), enableprototest, 104, 576);
  gtk_widget_set_size_request (enableprototest, 231, 23);

  enableprotousbtest = gtk_check_button_new_with_mnemonic (_("USB Protocol + All Connectivity Tests (All Rev)\n"));
  gtk_widget_show (enableprotousbtest);
  gtk_fixed_put (GTK_FIXED (fixed2), enableprotousbtest, 104, 616);
  gtk_widget_set_size_request (enableprotousbtest, 311, 23);

  label18 = gtk_label_new (_("Options"));
  gtk_widget_show (label18);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label18);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);
  gtk_widget_set_size_request (fixed3, 860, 736);

  remoteACsockets = gtk_entry_new ();
  gtk_widget_show (remoteACsockets);
  gtk_fixed_put (GTK_FIXED (fixed3), remoteACsockets, 528, 168);
  gtk_widget_set_size_request (remoteACsockets, 158, 25);

  applySettings2 = gtk_button_new ();
  gtk_widget_show (applySettings2);
  gtk_fixed_put (GTK_FIXED (fixed3), applySettings2, 768, 656);
  gtk_widget_set_size_request (applySettings2, 88, 80);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (applySettings2), alignment5);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Apply"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox6), label17, FALSE, FALSE, 0);

  discoverTime = gtk_entry_new ();
  gtk_widget_show (discoverTime);
  gtk_fixed_put (GTK_FIXED (fixed3), discoverTime, 528, 120);
  gtk_widget_set_size_request (discoverTime, 158, 25);

  saveButton2 = gtk_button_new ();
  gtk_widget_show (saveButton2);
  gtk_fixed_put (GTK_FIXED (fixed3), saveButton2, 664, 656);
  gtk_widget_set_size_request (saveButton2, 88, 80);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (saveButton2), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label94 = gtk_label_new_with_mnemonic (_("Save"));
  gtk_widget_show (label94);
  gtk_box_pack_start (GTK_BOX (hbox11), label94, FALSE, FALSE, 0);

  loadButton2 = gtk_button_new ();
  gtk_widget_show (loadButton2);
  gtk_fixed_put (GTK_FIXED (fixed3), loadButton2, 560, 656);
  gtk_widget_set_size_request (loadButton2, 88, 80);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (loadButton2), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label93 = gtk_label_new_with_mnemonic (_("Load"));
  gtk_widget_show (label93);
  gtk_box_pack_start (GTK_BOX (hbox10), label93, FALSE, FALSE, 0);

  discoverIterations = gtk_entry_new ();
  gtk_widget_show (discoverIterations);
  gtk_fixed_put (GTK_FIXED (fixed3), discoverIterations, 528, 304);
  gtk_widget_set_size_request (discoverIterations, 158, 25);

  label23 = gtk_label_new (_("Remote AC Unit Settings"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 344, 24);
  gtk_widget_set_size_request (label23, 184, 32);

  enableRemoteAC = gtk_check_button_new_with_mnemonic (_("Enable Remote AC Units"));
  gtk_widget_show (enableRemoteAC);
  gtk_fixed_put (GTK_FIXED (fixed3), enableRemoteAC, 104, 64);
  gtk_widget_set_size_request (enableRemoteAC, 176, 24);

  label25 = gtk_label_new (_("Power on to discover time (seconds)"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed3), label25, 96, 120);
  gtk_widget_set_size_request (label25, 240, 32);

  label27 = gtk_label_new (_("Number of AC Sockets in Use"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed3), label27, 104, 168);
  gtk_widget_set_size_request (label27, 200, 24);

  label98 = gtk_label_new (_("Discover Options"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed3), label98, 352, 256);
  gtk_widget_set_size_request (label98, 160, 24);

  label97 = gtk_label_new (_("Discover Iterations"));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed3), label97, 104, 304);
  gtk_widget_set_size_request (label97, 152, 32);

  SettingsLabel = gtk_label_new (_("Settings"));
  gtk_widget_show (SettingsLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), SettingsLabel);

  g_signal_connect ((gpointer) runButton, "clicked",
                    G_CALLBACK (on_runButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) quitButton, "clicked",
                    G_CALLBACK (on_quitButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) updateButton, "clicked",
                    G_CALLBACK (on_updateButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) stopButton, "clicked",
                    G_CALLBACK (on_stopButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) applySettings1, "clicked",
                    G_CALLBACK (on_applySettings1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_loadButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) saveButton, "clicked",
                    G_CALLBACK (on_saveButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) applySettings2, "clicked",
                    G_CALLBACK (on_applySettings2_clicked),
                    NULL);
  g_signal_connect ((gpointer) saveButton2, "clicked",
                    G_CALLBACK (on_saveButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) loadButton2, "clicked",
                    G_CALLBACK (on_loadButton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main, main, "main");
  GLADE_HOOKUP_OBJECT (main, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (main, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (main, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (main, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (main, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (main, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (main, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (main, image3, "image3");
  GLADE_HOOKUP_OBJECT (main, runButton, "runButton");
  GLADE_HOOKUP_OBJECT (main, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (main, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (main, image1, "image1");
  GLADE_HOOKUP_OBJECT (main, label9, "label9");
  GLADE_HOOKUP_OBJECT (main, quitButton, "quitButton");
  GLADE_HOOKUP_OBJECT (main, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (main, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (main, image4, "image4");
  GLADE_HOOKUP_OBJECT (main, label11, "label11");
  GLADE_HOOKUP_OBJECT (main, updateButton, "updateButton");
  GLADE_HOOKUP_OBJECT (main, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (main, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (main, image5, "image5");
  GLADE_HOOKUP_OBJECT (main, label12, "label12");
  GLADE_HOOKUP_OBJECT (main, stopButton, "stopButton");
  GLADE_HOOKUP_OBJECT (main, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (main, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (main, image2, "image2");
  GLADE_HOOKUP_OBJECT (main, label10, "label10");
  GLADE_HOOKUP_OBJECT (main, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (main, resultList, "resultList");
  GLADE_HOOKUP_OBJECT (main, label107, "label107");
  GLADE_HOOKUP_OBJECT (main, label108, "label108");
  GLADE_HOOKUP_OBJECT (main, label109, "label109");
  GLADE_HOOKUP_OBJECT (main, label110, "label110");
  GLADE_HOOKUP_OBJECT (main, label111, "label111");
  GLADE_HOOKUP_OBJECT (main, label112, "label112");
  GLADE_HOOKUP_OBJECT (main, label113, "label113");
  GLADE_HOOKUP_OBJECT (main, logViewWindow, "logViewWindow");
  GLADE_HOOKUP_OBJECT (main, logView, "logView");
  GLADE_HOOKUP_OBJECT (main, statusbar1, "statusbar1");
  GLADE_HOOKUP_OBJECT (main, testLabel, "testLabel");
  GLADE_HOOKUP_OBJECT (main, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (main, testLength, "testLength");
  GLADE_HOOKUP_OBJECT (main, testCycle, "testCycle");
  GLADE_HOOKUP_OBJECT (main, panosPerBatch, "panosPerBatch");
  GLADE_HOOKUP_OBJECT (main, label14, "label14");
  GLADE_HOOKUP_OBJECT (main, label29, "label29");
  GLADE_HOOKUP_OBJECT (main, usb1tolerance, "usb1tolerance");
  GLADE_HOOKUP_OBJECT (main, usb2tolerance, "usb2tolerance");
  GLADE_HOOKUP_OBJECT (main, usb3tolerance, "usb3tolerance");
  GLADE_HOOKUP_OBJECT (main, vgaTolerance, "vgaTolerance");
  GLADE_HOOKUP_OBJECT (main, applySettings1, "applySettings1");
  GLADE_HOOKUP_OBJECT (main, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (main, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (main, image7, "image7");
  GLADE_HOOKUP_OBJECT (main, label19, "label19");
  GLADE_HOOKUP_OBJECT (main, button14, "button14");
  GLADE_HOOKUP_OBJECT (main, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (main, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (main, image9, "image9");
  GLADE_HOOKUP_OBJECT (main, label92, "label92");
  GLADE_HOOKUP_OBJECT (main, saveButton, "saveButton");
  GLADE_HOOKUP_OBJECT (main, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (main, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (main, image8, "image8");
  GLADE_HOOKUP_OBJECT (main, label91, "label91");
  GLADE_HOOKUP_OBJECT (main, crcTolerance, "crcTolerance");
  GLADE_HOOKUP_OBJECT (main, prototolerance, "prototolerance");
  GLADE_HOOKUP_OBJECT (main, label15, "label15");
  GLADE_HOOKUP_OBJECT (main, enableBatchTesting, "enableBatchTesting");
  GLADE_HOOKUP_OBJECT (main, label24, "label24");
  GLADE_HOOKUP_OBJECT (main, label28, "label28");
  GLADE_HOOKUP_OBJECT (main, label22, "label22");
  GLADE_HOOKUP_OBJECT (main, label13, "label13");
  GLADE_HOOKUP_OBJECT (main, protousbtolerance, "protousbtolerance");
  GLADE_HOOKUP_OBJECT (main, enableDdrCrcTest, "enableDdrCrcTest");
  GLADE_HOOKUP_OBJECT (main, label70, "label70");
  GLADE_HOOKUP_OBJECT (main, enableVgaDdrTest, "enableVgaDdrTest");
  GLADE_HOOKUP_OBJECT (main, enableUsb1Test, "enableUsb1Test");
  GLADE_HOOKUP_OBJECT (main, enableUsb2Test, "enableUsb2Test");
  GLADE_HOOKUP_OBJECT (main, enableUsb3Test, "enableUsb3Test");
  GLADE_HOOKUP_OBJECT (main, enableprototest, "enableprototest");
  GLADE_HOOKUP_OBJECT (main, enableprotousbtest, "enableprotousbtest");
  GLADE_HOOKUP_OBJECT (main, label18, "label18");
  GLADE_HOOKUP_OBJECT (main, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (main, remoteACsockets, "remoteACsockets");
  GLADE_HOOKUP_OBJECT (main, applySettings2, "applySettings2");
  GLADE_HOOKUP_OBJECT (main, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (main, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (main, image6, "image6");
  GLADE_HOOKUP_OBJECT (main, label17, "label17");
  GLADE_HOOKUP_OBJECT (main, discoverTime, "discoverTime");
  GLADE_HOOKUP_OBJECT (main, saveButton2, "saveButton2");
  GLADE_HOOKUP_OBJECT (main, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (main, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (main, image11, "image11");
  GLADE_HOOKUP_OBJECT (main, label94, "label94");
  GLADE_HOOKUP_OBJECT (main, loadButton2, "loadButton2");
  GLADE_HOOKUP_OBJECT (main, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (main, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (main, image10, "image10");
  GLADE_HOOKUP_OBJECT (main, label93, "label93");
  GLADE_HOOKUP_OBJECT (main, discoverIterations, "discoverIterations");
  GLADE_HOOKUP_OBJECT (main, label23, "label23");
  GLADE_HOOKUP_OBJECT (main, enableRemoteAC, "enableRemoteAC");
  GLADE_HOOKUP_OBJECT (main, label25, "label25");
  GLADE_HOOKUP_OBJECT (main, label27, "label27");
  GLADE_HOOKUP_OBJECT (main, label98, "label98");
  GLADE_HOOKUP_OBJECT (main, label97, "label97");
  GLADE_HOOKUP_OBJECT (main, SettingsLabel, "SettingsLabel");

  return main;
}

